name: Task Management

on:
  issues:
    types: [edited, labeled, unlabeled, assigned, unassigned]

  project_card:
    types: [created, moved, converted, deleted]

  workflow_dispatch:

permissions:
  issues: write
  contents: write
  pull-requests: write
  repository-projects: write

env:
  TIMEZONE: "Asia/Seoul"
  PROJECT_NUMBER: "2"

jobs:
  track-status:
    if: |
      (github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issues' && !contains(github.event.issue.labels.*.name, 'report') && github.actor != 'github-actions[bot]' && !startsWith(github.event.issue.title, '.github/workflows/')) ||
      (github.event_name == 'project_card' && github.actor != 'github-actions[bot]'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements.txt

      - name: Update Task Status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd .github/scripts
          PYTHONPATH=. python task_report.py

  update-project:
    if: |
      github.event_name == 'issues' &&
      github.event.action == 'edited' &&
      contains(github.event.issue.title, 'Development Status Report')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements.txt

      - name: Update Project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd .github/scripts
          PYTHONPATH=. python project_updater.py
